### ISSUE TITLE
Bug - File Upload Component

### ISSUE THREAD

**Issue by Seanaseire** [scania/corporate-ui#546] opened 2020-02-18 10:51 UTC
**Describe the bug**  
Due to the recent u80 of Chrome, the file upload component no longer works.

**To Reproduce**   
1. Create a webpage with file upload component implemented as such

```
<link  rel="import" href="https://static.scania.com/build/global/3.5.2/components/file-upload/file-upload.html">

<c-file-upload name="uxlib-file-input" multiple max-file-size="1000" accept="image/*"></c-file-upload>
```
**Version of Corporate-ui**  
 Version 3.5.5

**Desktop information:**  
 - Browser Chrome
 - Version 80
 - OS: Windows 10

**Comment by helloimela** [comment] 2020-07-01 13:31
Hello, thank you for reporting the issue!
This problem appear probably caused by `display='inline'` attribute. Because file upload with drop area is working properly. 

Unfortunately, we are limited in resources now and we decided to focus on the development of corporate-ui v4 which will provide a more sustainable & flexible solution since Polymer v1 which is used in corporate-ui 3 is not supported by Chrome and other major browsers. (You can see a warning in the console if you are still using corporate-ui 3).
We strongly suggest everyone move to corporate-ui 4 and we would like to ask your help and the community to solve this issue together.
If you think it is still valuable to fix this issue in corporate-ui 3, please help us fix this problem and create a pull-request.

Right now we have no plan to create file-upload component in CUI 4. If you think this feature (file upload component) is important and need to be implemented in corporate-ui 4, please contact our team! Or you can also develop the component yourself and contributing to the bigger community :)

Thanks!
P.S. We will close this issue soon if we don't receive update from you or from others in this thread :)

**Comment by helloimela** [comment] 2020-09-01 11:59
Hello @Seanaseire , any update on this issue? Is this a blocker in your project? As mentioned above, it will probably implemented in version 4 and not 3, if there are any request arise regarding file-upload component.

**Comment by helloimela** [comment] 2020-09-17 06:15
A month ago we announced about deprecation of Corporate UI 3 in 1 year, we will only provide support for severe bugs. We will close this issue for now. Please check solution in Corporate UI 4 and if the problem appears, we will solve it in version 4.
Link to annoucement in Teams: [link](https://teams.microsoft.com/l/message/19:7a4c1fa7280f4fcdbda85a6758b22b01@thread.skype/1598345607959?tenantId=3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac&groupId=79f9bfeb-73e2-424d-9477-b236191ece5e&parentMessageId=1598345607959&teamName=Scania%20Digital%20Design%20System&channelName=Announcements&createdTime=1598345607959)

**Closed by helloimela** 2020-09-17 06:15 UTC
Labels: Version 3, bug
